const ProductData = [
  {
    name: "Adidas",
    id: "01",
    inCart: false,
    image: "./products/shoes1.png",
    category: "Running Shoes",
    qty:1,
    price: "10",
    mrp: "13",
  },
  {
    name: "Hush Puppies",
    id: "02",
    inCart: false,
    image: "./products/shoes2.png",
    category: "Lightweight Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Liberty",
    id: "03",
    inCart: false,
    image: "./products/shoes3.png",
    category: "Trail Shoes",
    qty:1,
    price: "14",
    mrp: "15",
  },
  {
    name: "Crocs",
    id: "04",
    inCart: false,
    image: "./products/shoes4.png",
    category: "Motion Control Shoes",
    qty:1,
    price: "11",
    mrp: "13",
  },
  {
    name: "Clarks",
    id: "05",
    inCart: false,
    image: "./products/shoes5.png",
    category: "Cushioned Shoes",
    qty:1,
    price: "12",
    mrp: "18",
  },
  {
    name: "Nike",
    id: "06",
    inCart: false,
    image: "./products/shoes6.png",
    category: "Running Shoes",
    qty:1,
    price: "10",
    mrp: "11",
  },
  {
    name: "Timberland",
    id: "07",
    inCart: false,
    image: "./products/shoes7.png",
    category: "Running Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Peter England",
    id: "08",
    inCart: false,
    image: "./products/shoes8.png",
    category: "Lightweight Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Arrow",
    id: "09",
    inCart: false,
    image: "./products/shoes9.png",
    category: "Cushioned Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Van Heusen",
    id: "10",
    inCart: false,
    image: "./products/shoes10.png",
    category: "Running Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Tata International",
    id: "11",
    inCart: false,
    image: "./products/shoes11.png",
    category: "Trail Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },
  {
    name: "Louis Philippe",
    id: "12",
    inCart: false,
    image: "./products/shoes12.png",
    category: "Cushioned Shoes",
    qty:1,
    price: "12",
    mrp: "16",
  },

];

export default ProductData;
